[webservers]
web-1 ansible_host=111.88.242.247 fqdn=fhmm12bdct95sq7tg3v0.auto.internal
web-2 ansible_host=111.88.246.140 fqdn=fhmqpeo6mekhab3qjdos.auto.internal

[databases]
main ansible_host=111.88.254.223 fqdn=fhmbge2f49rb0j9blma2.auto.internal
replica ansible_host=51.250.2.149 fqdn=fhmkhhdfhrrbuipcmua4.auto.internal

[storage]
storage ansible_host=84.201.129.176 fqdn=fhmper4p989hqhpkhh3v.auto.internal
